### ISSUE TITLE
Fetch delays and server-side rendering

### ISSUE THREAD

**Issue by josephdburdick** [RyanCCollins/react-weekly#4]
Hello, just wondering why this appears to not be SSR-enabled since you have everything in place for it to be.  Also why are there forced delays on data fetching?  Thanks in advance!

**Comment by RyanCCollins** [comment]
Hey @josephdburdick, the app is server-rendered, but the index.html that is generated from the webpack script means that the app is not server-rendered on the home page.  That was just a mistake on my part and I haven't gotten around to fixing it for this project.

The forced delays, I am not totally sure what that means.  Sometimes I will add setTimeouts to fetch requests because the app appears jumpy when there is no delay because the loading can happen in just a few milliseconds.  Anyways, can you show me the example you are referring to?

**Comment by josephdburdick** [comment]
Hi, I was for some reason under the impression that this was SSR-enabled but I was mistaken. About the forced delays... I remember seeing them on a previous pull but no longer see the message. Closing.
